### PR TITLE
Fix: WebP images can't be sent as media.

### LINKED ISSUE #1483: Cannot send .webp images
### Steps to reproduce

1. Download some funny memes in .webp format
2. Try to send them to your friends by picking via "Photo & Video Library"
3. Cry because you cannot send a funny meme to your friends

#### What did you expect?
Successfully sending the meme to friends 😭

#### What happened instead?
"Failed processing media to upload, please try again"

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

v0.2.3 downlaoded from GitHub Releases tab

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

- Replaces `inputStream` parameter in  `processImage` function with a `inputStreamProvider` parameter so we can create as much input streams as we need to.
- Add WebP files to the mime types that can't be compressed, as some WebP files are animated.

## Motivation and context

To compress images we used a `BufferedInputStream` to read its bounds and then restore its buffer position to 0 so we can read the actual image only. This was failing for WebP types, and it might also fail for very large images, so we need to actually have 2 input streams. Also, WebP files might be animated so compressing them may be a mistake.

Fixes #1483.

## Tests

- Download some WebP file.
- Try to send it from the gallery picker in a room. If it works, it's fixed.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 11

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

File: libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/ImageCompressor.kt [hunk 1]
```diff
@@ -98,13 +102,11 @@ class ImageCompressor @Inject constructor(
             is ResizeMode.None -> return
         }
         // Read bounds only
-        inputStream.mark(inputStream.available())
         options.inJustDecodeBounds = true
         BitmapFactory.decodeStream(inputStream, null, options)
         // Set sample size based on the outWidth and outHeight
         options.inSampleSize = options.calculateInSampleSize(width, height)
         // Now read the actual image and rotate it to match its metadata
-        inputStream.reset()
```
Comment (bmarty) [inline libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/ImageCompressor.kt:107]: I was about to ask if this could be removed. 👍  (the comment above is outdated/misplaced, but this is not new)

**Review by bmarty — APPROVED** [review]
Perfect, thanks!

File: libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/ImageCompressor.kt (hunk 1 above)
Comment (jmartinesp) [reply libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/ImageCompressor.kt:107]: Good catch, I completely missed it! Fixed in https://github.com/vector-im/element-x-android/pull/1501/commits/4eebd8e935e9f71a8cf8b7617069f4433d877dfc
