### PR TITLE
Use user friendly error messages in login following iOS logic

### LINKED ISSUE #132: Make error when typing in wrong password user friendly
### Steps to reproduce

1. At login, type in wrong password and try to proceed

#### What did you expect?
User friendly error saying that the password or username is wrong (or something that makes sense)

#### What happened instead?
Not user friendly error and the text with the light theme looks too light to read (note that I'm on Graphene, not Android!)

Screenshot_20230306-084501
Screenshot_20230306-084133

### Your phone model

_No response_

### Operating system version

Graphene OS

### Application version and app store

https://github.com/vector-im/element-x-android/pull/100#issuecomment-1452016588

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
Also, fix dialog colors.

Fixes #132.

### CODE REVIEW

File: libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/components/dialogs/ConfirmationDialog.kt [hunk 1]
```diff
@@ -48,9 +48,9 @@ fun ConfirmationDialog(
     onThirdButtonClicked: () -> Unit = {},
     onDismiss: () -> Unit = {},
     shape: Shape = AlertDialogDefaults.shape,
-    containerColor: Color = MaterialTheme.colorScheme.surfaceVariant,
-    iconContentColor: Color = MaterialTheme.colorScheme.onSurfaceVariant,
-    titleContentColor: Color = MaterialTheme.colorScheme.onSurfaceVariant,
+    containerColor: Color = MaterialTheme.colorScheme.surface,
```
Comment (bmarty) [inline libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/components/dialogs/ConfirmationDialog.kt:51]: Why not using `AlertDialogDefaults.containerColor` (this is the default for `AlertDialog`). I am not 100% sure, but since now we stick to `material3`, it would have more sense to keep default behavior.

File: libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/components/dialogs/ErrorDialog.kt [hunk 2]
```diff
@@ -46,9 +40,9 @@ fun ErrorDialog(
     submitText: String = stringResource(id = StringR.string.ok),
     onDismiss: () -> Unit = {},
     shape: Shape = AlertDialogDefaults.shape,
-    containerColor: Color = MaterialTheme.colorScheme.surfaceVariant,
-    iconContentColor: Color = MaterialTheme.colorScheme.onSurfaceVariant,
-    titleContentColor: Color = MaterialTheme.colorScheme.onSurfaceVariant,
+    containerColor: Color = MaterialTheme.colorScheme.surface,
```
Comment (bmarty) [inline libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/components/dialogs/ErrorDialog.kt:43]: Same remark.

**Review by bmarty — APPROVED** [review]
LGTM. Some screenshots have been touched, but I cannot see the diff.

Also maybe add the error case during the login flow in maestro test by entering a wrong password before [this point](https://github.com/vector-im/element-x-android/blob/develop/.maestro/tests/account/login.yaml#L15)?

File: libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/components/dialogs/ConfirmationDialog.kt (hunk 1 above)
Comment (jmartinesp) [reply libraries/designsystem/src/main/kotlin/io/element/android/libraries/designsystem/components/dialogs/ConfirmationDialog.kt]: Done in [`67374f8`](https://github.com/vector-im/element-x-android/pull/174/commits/67374f8fcbf9509aa8d671a1cd0f6989d7133ea6).

**Comment by jmartinesp** [comment]
> Improve Maestro tests with wrong password dialog

Sure, it's done in [`2a8ae31`](https://github.com/vector-im/element-x-android/pull/174/commits/2a8ae31839803c3e7359eab1fb4cf792688402db). Let's hope the CI passes, but it did locally 🤞 .

**Comment by jmartinesp** [comment]
I just added tests for error messages in [`bfc484e`](https://github.com/vector-im/element-x-android/pull/174/commits/bfc484e0e081a002a9642cb86b1ef30d10963331), but if we think that's going too far with testing I can revert this commit.
