### PR TITLE
Fix the orientation of sent images

### LINKED ISSUE #1134: Taking photos in-app makes them go sideways
### Steps to reproduce

1. Open room
2. Take photo
3. Preview is correct orientation
4. Thumbnails and downloads are not

#### What did you expect?

The world to be at 0 degrees, not 90.

#### What happened instead?

<details>
<summary>A photo adventure</summary>

Screenshot_20230823-183426

Screenshot_20230823-183433

Screenshot_20230823-183521

Screenshot_20230823-183524

</details>

### Your phone model

Pixel 5

### Operating system version

Android 13

### Application version and app store

0.1.2 (40001020) - google play

### Homeserver

t2l.io

### Will you send logs?

No

### Are you willing to provide a PR?

No

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Read `EXIF` metadata for orientation *before* decoding the bitmap, from another `InputStream`. This gives us a correct orientation value and should rotate the image to send as needed.

## Motivation and context

Fixes #1134 .

## Tests

On some devices, sending a picture that was just taken from the camera is enough. I couldn't reproduce this in my device, so the alternate solution I found was:

- Download https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_3.jpg or any of the other samples.
- Send it through the 'photo & video library' option.
- Verify the image has the same orientation.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 11

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

File: libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/ImageCompressor.kt [hunk 1]
```diff
@@ -37,17 +37,18 @@ class ImageCompressor @Inject constructor(
...
      * Decodes the [inputStream] into a [Bitmap] and applies the needed transformations (rotation, scale) based on [resizeMode], then writes it into a
-     * temporary file using the passed [format] and [desiredQuality].
+     * temporary file using the passed [format], [orientation] and [desiredQuality].
      * @return a [Result] containing the resulting [ImageCompressionResult] with the temporary [File] and some metadata.
      */
     suspend fun compressToTmpFile(
         inputStream: InputStream,
         resizeMode: ResizeMode,
         format: Bitmap.CompressFormat = Bitmap.CompressFormat.JPEG,
+        orientation: Int = 0,
```
Comment (bmarty) [inline libraries/mediaupload/impl/src/main/kotlin/io/element/android/libraries/mediaupload/ImageCompressor.kt:47]: Maybe use named const instead of 0.
```suggestion
        orientation: Int = ExifInterface.ORIENTATION_UNDEFINED,
```
or just remove the default parameter value.

**Review by bmarty — APPROVED** [review]
LGTM, thanks.
