### PR TITLE
Fix crash when user wants to use the camera

### LINKED ISSUE #1395: [Crash] Crash when trying to take a picture
To update the room avatar or the user avatar

> Thread: main, Exception: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) } from ProcessRecord{5dad0e3 19140:io.element.android.x/u0a354} (pid=19140, uid=10354) with revoked permission android.permission.CAMERA

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Camera permission is not required when using the external app, except when the Android Manifest contains the CAMERA permission. And this permission has been added when we integrated Element Call.

This PR ensures that the CAMERA permission is provided when user want to:
- take a photo or record a video to send as attachement
- take a photo to set a room avatar when creating a room
- take a photo to set a room avatar when editing a room
- take a photo to set the user profile

Also contains some cleanup on the codebase, and some new localazy strings.

At some point we will need to revisit how we manage the permissions, since this is also done for the location permission, in the dedicated module.

## Motivation and context

Fixes #1395

## Tests

- Test the use case in the description

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/vector-im/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

File: features/createroom/impl/src/main/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomNode.kt [hunk 1]
```diff
@@ -58,11 +60,13 @@ class ConfigureRoomNode @AssistedInject constructor(
     @Composable
     override fun View(modifier: Modifier) {
         val state = presenter.present()
+        val context = LocalContext.current
         ConfigureRoomView(
             state = state,
             modifier = modifier,
             onBackPressed = this::navigateUp,
             onRoomCreated = this::onRoomCreated,
+            onOpenSystemSettings = { context.openAppSettingsPage() }
```
Comment (julioromano) [inline features/createroom/impl/src/main/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomNode.kt:69]: Maybe this can be moved into PermissionsPresenter itself?

File: features/createroom/impl/src/main/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomPresenter.kt [hunk 2]
```diff
@@ -52,10 +55,15 @@ class ConfigureRoomPresenter @Inject constructor(
     private val mediaPickerProvider: PickerProvider,
     private val mediaPreProcessor: MediaPreProcessor,
     private val analyticsService: AnalyticsService,
+    permissionsPresenterFactory: PermissionsPresenter.Factory,
 ) : Presenter<ConfigureRoomState> {
 
+    private val cameraPermissionPresenter: PermissionsPresenter = permissionsPresenterFactory.create(android.Manifest.permission.CAMERA)
+    private var pendingPermissionRequest = false
```
Comment (julioromano) [inline features/createroom/impl/src/main/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomPresenter.kt:62]: Maybe this should be a `remember { mutableStateOf() }` ?

Moreover, perhaps this could also be hoisted to `PermissionsPresenter` to simplify the client side impementation.

File: features/createroom/impl/src/test/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomPresenterTests.kt [hunk 3]
```diff
@@ -182,6 +185,10 @@ class ConfigureRoomPresenterTests {
             // From camera
             val uriFromCamera = Uri.parse(AN_URI_FROM_CAMERA)
             fakePickerProvider.givenResult(uriFromCamera)
+            assertThat(newState.cameraPermissionState.permissionGranted).isFalse()
```
Comment (julioromano) [inline features/createroom/impl/src/test/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomPresenterTests.kt:188]: Shouldn't we also test that when permission is not granted we catually call into the PermissionsPresenter to request it?

File: features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/notifications/NotificationsOptInPresenter.kt [hunk 4]
```diff
@@ -65,7 +65,7 @@ class NotificationsOptInPresenter @AssistedInject constructor(
                     if (notificationsPermissionsState.permissionGranted) {
                         callback.onNotificationsOptInFinished()
                     } else {
-                        notificationsPermissionsState.eventSink(PermissionsEvents.OpenSystemDialog)
+                        notificationsPermissionsState.eventSink(PermissionsEvents.AskPermissionToUser)
```
Comment (julioromano) [inline features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/notifications/NotificationsOptInPresenter.kt:68]: In similar android contexts this is usually called "RequestPermissions".

**Review by julioromano — APPROVED** [review]
LGTM, just some suggestions for the future.

File: features/createroom/impl/src/main/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomNode.kt (hunk 1 above)
Comment (bmarty) [reply features/createroom/impl/src/main/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomNode.kt:69]: yes, a bit simpler: dd5d67d18622d00c87ad4a25b00e9bbde97a7f93

File: features/createroom/impl/src/test/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomPresenterTests.kt (hunk 3 above)
Comment (bmarty) [reply features/createroom/impl/src/test/kotlin/io/element/android/features/createroom/impl/configureroom/ConfigureRoomPresenterTests.kt:188]: You're right, there is a missing test. I will ad it.

**Comment by bmarty** [comment]
@julioromano should be fine now, the CI should turn green.
