### PR TITLE
Settings UI

### LINKED ISSUE #518: [Navigation] After sending a rageshake, the screen is empty
### Steps to reproduce

1. Send a bug report

#### What did you expect?

The bug report is sent and the app goes back to the previous screen

#### What happened instead?

The bug report is sent, but the screen does not popup and becomes black.

The user has to click on the back button to go back to the previous screen.

### Your phone model

_No response_

### Operating system version

_No response_

### Application version and app store

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### Are you willing to provide a PR?

No

### LINKED ISSUE #578: Add links to legal data in the settings and update design on settings.
In order to comply with the PlayStore requirement.

FTR, this is what we have in the current Element Android application:

|Settings|Legals|
|-|-|
|image|image|

For Element X, we can keep the 3 first items for now: Copyright, Acceptable Use Policy and Privacy policy.
When the user clicks any item, the app is opening the link to a Custom Chrome Tab if available or in any available Web browser.

Urls to use are the same as EA:
- https://element.io/copyright
- https://element.io/privacy
- https://element.io/acceptable-use-policy-terms

**Design**: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=1096%3A78619&mode=design&t=rOKcQBnzrER5nC3l-1

### PR DESCRIPTION
**Pull request by bmarty**
Iterate on the settings UI. See the design [here](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=1096%3A78619&mode=design&t=rOKcQBnzrER5nC3l-1) .

Note: cannot get the "help" and "developer" icons render as in the design (I am using `Icons.Outlined.Help` and `Icons.Outlined.DeveloperMode`) Maybe a bug in the Compose lib?:

|Expected|Actual|
|-|-|
|image|image|

Reorganize settings hierarchy and add legal screen. Closes #578.

There is some side effects on RoomDetails screen, since this screen uses the same component than for the preferences. I think it is still OK.

Disable Rageshake feature by default, can be enabled in developer's settings.

Bonus: fixes #518

### CODE REVIEW

File: libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt [hunk 1]
```diff
@@ -41,44 +37,51 @@ import io.element.android.libraries.designsystem.theme.components.Text
...
 fun MatrixUserHeader(
-    matrixUser: MatrixUser,
+    matrixUser: MatrixUser?,
     modifier: Modifier = Modifier,
-    onClick: () -> Unit = {},
+    // onClick: () -> Unit = {},
 ) {
-    Column(
+    if (matrixUser == null) {
+        return MatrixUserHeaderPlaceholder(modifier = modifier)
```
Comment (ElementBot) [inline libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt:49]: - :warning: Modifiers should only be used once and by the root level layout of a Composable. This is true even if appended to or with other modifiers e.g. 'modifier.fillMaxWidth()'.

Use Modifier (with a capital 'M') to construct a new Modifier that you can pass to other composables.

See https://mrmans0n.github.io/compose-rules/rules/#dont-re-use-modifiers for more information.

File: libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt [hunk 2]
```diff
@@ -41,44 +37,51 @@
...
+    }
+    Row(
```
Comment (ElementBot) [inline libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt:51]: - :warning: Modifiers should only be used once and by the root level layout of a Composable. This is true even if appended to or with other modifiers e.g. 'modifier.fillMaxWidth()'.

Use Modifier (with a capital 'M') to construct a new Modifier that you can pass to other composables.

See https://mrmans0n.github.io/compose-rules/rules/#dont-re-use-modifiers for more information.

File: libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt [hunk 3]
```diff
@@ -41,44 +37,65 @@ import io.element.android.libraries.designsystem.theme.components.Text
...
+        )
+    }
+}
+
+@Composable
+private fun MatrixUserHeaderContent(
     matrixUser: MatrixUser,
     modifier: Modifier = Modifier,
-    onClick: () -> Unit = {},
+    // onClick: () -> Unit = {},
```
Comment (julioromano) [inline libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt:63]: Is this (and the other) comment a leftover or is it intended?

File: features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutState.kt [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.element.android.features.preferences.impl.about
+
+// TODO add your ui models. Remove the eventSink if you don't have events.
```
Comment (julioromano) [inline features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutState.kt:19]: Perhaps unwanted todo line?

File: features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutEvents.kt [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.element.android.features.preferences.impl.about
+
+sealed interface AboutEvents {
+    object MyEvent : AboutEvents
```
Comment (julioromano) [inline features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutEvents.kt:20]: Perhaps unwanted file?

File: features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/analytics/AnalyticsSettingsEvents.kt [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.element.android.features.preferences.impl.analytics
+
+sealed interface AnalyticsSettingsEvents {
```
Comment (julioromano) [inline features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/analytics/AnalyticsSettingsEvents.kt:19]: Perhaps unwanted file?

**Review by julioromano — COMMENTED** [review]
A few comments

File: libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt (hunk 3 above)
Comment (bmarty) [reply libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt:63]: Actually at some point we will have a onClick action here, but by keeping the `onClick` on the modifier, we have the ripple effect, but no action which looks like a bug. So I commented out that, then the param appears as unused, so I commented it out also.

I have added a TODO to explain why I do not really want to remove this code.

File: libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/user/CurrentUserProvider.kt [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.element.android.libraries.matrix.api.user
+
+import io.element.android.libraries.matrix.api.MatrixClient
+import javax.inject.Inject
+
+class CurrentUserProvider @Inject constructor(
```
[the remark this answers is not in the document]
Comment (bmarty) [reply libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/user/CurrentUserProvider.kt]: You are right: dfff72e29022989ec314ec94c48e2c9b382d8b84

File: libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt (hunk 3 above)
Comment (bmarty) [reply libraries/matrixui/src/main/kotlin/io/element/android/libraries/matrix/ui/components/MatrixUserHeader.kt:64]: c8afa7ef2e42ae842dd8435cb12421c58543c22f

File: features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutState.kt (hunk 4 above)
Comment (bmarty) [reply features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutState.kt]: Removed.

File: features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutEvents.kt (hunk 5 above)
Comment (bmarty) [reply features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/about/AboutEvents.kt]: Yes, I did not really want to delete the (generated) files because, when we will need it, we will have to create theme again, but I have done the cleanup in 5dd0a1b477ed6c02f18155a8291a3b7c8b046fed

File: features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/analytics/AnalyticsSettingsEvents.kt (hunk 6 above)
Comment (bmarty) [reply features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/analytics/AnalyticsSettingsEvents.kt]: deleted.

File: tools/check/forbidden_strings_in_code.txt [hunk 8]
```diff
@@ -72,7 +72,7 @@ DO NOT COMMIT
 ^      /\*
 
 ### unnecessary parenthesis around numbers, example: " (0)"
- \(\d+\)
+ \(\d+\)[^"]
```
[the remark this answers is not in the document]
Comment (bmarty) [reply tools/check/forbidden_strings_in_code.txt:75]: This check ensure that we are not using unnecessary parenthsis around integer, such as `(1)` for instance.
But there has been a false positive due to this line:

https://github.com/vector-im/element-x-android/blob/23a2a5b1699248b7c05e7a80d0e4c7b983404c09/features/preferences/impl/src/main/kotlin/io/element/android/features/preferences/impl/root/PreferencesRootStateProvider.kt#L24

The change ensure that if the number is followed by `"` it's OK. I admit this is ugly though :).

**Review by julioromano — APPROVED** [review]
